-- PostgreSQL-схема без триггеров
-- Основные таблицы:
-- users, groups, group_memberships, subjects, task_items,
-- task_progress, study_sessions, study_session_pauses


-- 1. users

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    system_role VARCHAR(20) NOT NULL DEFAULT 'student',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT chk_users_system_role
        CHECK (system_role IN ('student', 'admin'))
);


-- 2. groups


CREATE TABLE groups (
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    group_name VARCHAR(100) NOT NULL,
    description TEXT,

    owner_user_id INTEGER NOT NULL,

    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_groups_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
);

-- 3. group_memberships

-- Пользователь может вступить в одну и ту же группу только один раз.
-- Поэтому первичный ключ составной: (group_id, user_id).

CREATE TABLE group_memberships (
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    group_role VARCHAR(20) NOT NULL DEFAULT 'member',

    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at TIMESTAMPTZ,

    CONSTRAINT pk_group_memberships
        PRIMARY KEY (group_id, user_id),

    CONSTRAINT fk_group_memberships_group
        FOREIGN KEY (group_id)
        REFERENCES groups(group_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_group_memberships_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_group_memberships_role
        CHECK (group_role IN ('member', 'group_owner')),

    CONSTRAINT chk_group_memberships_left_at
        CHECK (left_at IS NULL OR left_at >= joined_at)
);

-- 4. subjects

-- Предмет принадлежит либо пользователю, либо группе.
-- Одновременно принадлежать пользователю и группе предмет не может.

CREATE TABLE subjects (
    subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    subject_name VARCHAR(100) NOT NULL,
    description TEXT,

    owner_user_id INTEGER,
    owner_group_id INTEGER,

    is_archived BOOLEAN NOT NULL DEFAULT false,
    is_default BOOLEAN NOT NULL DEFAULT false,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_subjects_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_subjects_owner_group
        FOREIGN KEY (owner_group_id)
        REFERENCES groups(group_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_subjects_owner_xor
        CHECK (
            (owner_user_id IS NOT NULL AND owner_group_id IS NULL)
            OR
            (owner_user_id IS NULL AND owner_group_id IS NOT NULL)
        )
);


-- 5. task_items

-- Задача принадлежит либо пользователю, либо группе.
-- Индивидуальное выполнение задачи хранится отдельно в task_progress.

CREATE TABLE task_items (
    task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(200) NOT NULL,
    description TEXT,

    subject_id INTEGER NOT NULL,

    owner_user_id INTEGER,
    owner_group_id INTEGER,

    deadline_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    task_link VARCHAR(500),
    max_points INTEGER,

    is_archived BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT fk_task_items_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(subject_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_task_items_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_task_items_owner_group
        FOREIGN KEY (owner_group_id)
        REFERENCES groups(group_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_task_items_owner_xor
        CHECK (
            (owner_user_id IS NOT NULL AND owner_group_id IS NULL)
            OR
            (owner_user_id IS NULL AND owner_group_id IS NOT NULL)
        ),

    CONSTRAINT chk_task_items_max_points
        CHECK (max_points IS NULL OR max_points >= 0)
);


-- 6. task_progress

-- Одна запись task_progress хранит прогресс одного пользователя по одной задаче.
-- Поля earned_points здесь нет, потому что в этой версии баллы не считаются.

CREATE TABLE task_progress (
    task_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    progress_status VARCHAR(20) NOT NULL DEFAULT 'not_started',

    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_task_progress
        PRIMARY KEY (task_id, user_id),

    CONSTRAINT fk_task_progress_task
        FOREIGN KEY (task_id)
        REFERENCES task_items(task_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_task_progress_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_task_progress_status
        CHECK (progress_status IN ('not_started', 'in_progress', 'completed', 'dismissed')),

    CONSTRAINT chk_task_progress_completed_at
        CHECK (
            (progress_status <> 'completed')
            OR
            (completed_at IS NOT NULL)
        ),

    CONSTRAINT chk_task_progress_started_completed_order
        CHECK (
            completed_at IS NULL
            OR started_at IS NULL
            OR completed_at >= started_at
        )
);


-- 7. study_sessions

-- Учебная сессия всегда принадлежит пользователю и предмету.
-- task_id необязателен: NULL означает свободное изучение без конкретной задачи.

CREATE TABLE study_sessions (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    task_id INTEGER,

    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    session_status VARCHAR(20) NOT NULL DEFAULT 'active',

    CONSTRAINT fk_study_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_study_sessions_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects(subject_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_study_sessions_task
        FOREIGN KEY (task_id)
        REFERENCES task_items(task_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_study_sessions_status
        CHECK (session_status IN ('active', 'paused', 'completed', 'cancelled')),

    CONSTRAINT chk_study_sessions_time_order
        CHECK (ended_at IS NULL OR ended_at >= started_at)
);


-- 8. study_session_pauses

-- Одна учебная сессия может иметь несколько пауз.
-- resumed_at = NULL означает, что пауза сейчас открыта.

CREATE TABLE study_session_pauses (
    pause_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id INTEGER NOT NULL,

    paused_at TIMESTAMPTZ NOT NULL,
    resumed_at TIMESTAMPTZ,

    CONSTRAINT fk_study_session_pauses_session
        FOREIGN KEY (session_id)
        REFERENCES study_sessions(session_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_study_session_pauses_time_order
        CHECK (resumed_at IS NULL OR resumed_at >= paused_at)
);


-- Замечания для следующих версий

-- Следующие правила важны, но в этой версии не полностью контролируются схемой,
-- потому что для них нужны триггеры или проверка на уровне прикладной логики:
--
-- 1. Личная задача должна быть связана с личным предметом того же пользователя.
-- 2. Групповая задача должна быть связана с групповым предметом той же группы.
-- 3. Если study_sessions.task_id не равен NULL,
--    то study_sessions.subject_id должен совпадать с task_items.subject_id.
-- 4. При создании групповой задачи должны создаваться записи task_progress
--    для всех активных участников группы.
-- 5. При вступлении пользователя в группу записи task_progress должны создаваться
--    только для актуальных групповых задач.
-- 6. При выходе пользователя из группы невыполненные записи task_progress
--    по задачам этой группы могут физически удаляться по выбранному бизнес-правилу.
